server:
  port: 8080

spring:
  application:
    name: book-service

  # Configure Feign client
  cloud:
    feign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000




